<a href="https://colab.research.google.com/github/HuNt07/nlp/blob/main/natural_language_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Natural Language Processing

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv('financial_audits.tsv', delimiter = '\t', quoting = 3)

## Cleaning the texts, Stemming, Removing stop words, Creating Corpus

In [ ]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, 11669):
  review = re.sub('[^a-zA-Z]', ' ', str(dataset['Sentence'][i]))
  pattern = re.compile(r'https?://\S+|www\.\S+')
  review = re.sub(pattern, ' ', str(dataset['Sentence'][i]))
  review = re.sub('[\w\.-]+@[\w\.-]+\.\w+', ' ', str(dataset['Sentence'][i]))
  review = review.lower()
  review = review.split() 
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
  review = ' '.join(review)
  corpus.append(review)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
print(corpus)

['$esi lows, $1.50 $2.50 bk real possibl', "last quarter 2010 , componenta 's net sale doubl eur131m eur76m period year earlier , move zero pre-tax profit pre-tax loss eur7m .", 'accord finnish-russian chamber commerc , major construct compani finland oper russia .', 'swedish buyout firm sold remain 22.4 percent stake , almost eighteen month take compani public finland .', '$spi surpris see green close', "shell' $70 billion bg deal meet sharehold skeptic", 'ssh commun secur corp stock exchang releas octob 14 , 2008 2:45 pm compani updat full year outlook estim result remain loss full year .', "kone 's net sale rose 14 % year-on-year first nine month 2008 .", "stockmann depart store total floor space 8,000 squar metr stockmann 's invest project price tag eur 12 million .", 'circul revenu increas 5 % finland 4 % sweden 2008 .', '$sap q1 disappoint #softwar licens down. real problem? #cloud growth trail $msft $orcl $goog $crm $adb https://t.co/jndphllzq5', 'subdivis made sale revenu last 

## Creating the Bag of Words model

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=9100)
X = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:, -1].values


## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

## Training the Naive Bayes model on the Training set

In [ ]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train, y_train)

MultinomialNB()

## Predicting the Test set results

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 1  1]
 [ 0 -1]
 [-1 -1]
 ...
 [-1 -1]
 [ 1  1]
 [ 1  1]]


## Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[211  93  34]
 [152 993  73]
 [ 53 152 573]]


0.7613538988860326

## Pickle

In [ ]:
#import sys

In [ ]:

#print(sys.getsizeof(classifier))


In [ ]:
# import pickle 
# with open('model.pickle', 'wb') as f:
#     pickle.dump(saveed_model.sav, f)

In [ ]:
import pickle
saved_model=open('saved_model.sav','wb')
pickle.dump(classifier,saved_model)
saved_model.close()

new_model='saved_model.sav'
new_classifier=pickle.load(open(new_model,'rb'))
new_classifier.score(X_test,y_test)



0.7613538988860326

In [ ]:
arr=["bank is in loss"]
s=cv.transform(arr).toarray()
new_classifier.predict(s) 


array([1])